name: 友链添加申请
description: 在本站添加友链的申请
title: 友链添加申请
labels: ["friend-link"]
body:
- type: checkboxes
  id: agree
  attributes:
    label: 确认
    description: 请确认您满足可添加友链的需求
    options:
      - label: 已了解 https://qwq.blue/add-yours 中添加站点的需求
        required: true
- type: input
  id: site-name
  attributes:
    label: 站点名称
    description: 你的站点名字
    placeholder: Silvaire's Blog
  validations:
    required: true
- type: input
  id: site-desc
  attributes:
    label: 站点简介
    description: 站点的描述（可选）
    placeholder: 生如夏花之绚烂，死如秋叶之静美。
- type: input
  id: site-link
  attributes:
    label: 站点地址
    description: 站点的主页链接
    placeholder: https://qwq.blue
  validations:
    required: true
- type: input
  id: site-img
  attributes:
    label: 站点头像
    description: 你的站点头像链接（推荐）
    placeholder: https://wsrv.nl/?url=avatars.githubusercontent.com/u/184231508
