name: 友链添加申请
description: 在本站添加友链的申请
title: 友链添加申请
labels: ["friend-link"]
body:
- type: checkboxes
  id: agree
  attributes:
    label: 确认
    description: 请确认您满足可添加友链的需求，如违反则后果自负。
    options:
      - label: 在大陆地区需能正常访问，同时能维持站点的稳定运行
        required: true
      - label: 一年内更新过博客
        required: true
      - label: 头像能长期稳定地打开
        required: true
      - label: 已添加本站友链
        required: true
      - label: 无含有色情、赌博、虚假医药、高版权风险、涉政等不宜的内容
        required: true
      - label: 您的申请不是修改信息
        required: true
- type: input
  id: site-name
  attributes:
    label: 标题
    description: Title
    placeholder: Silvaire's Blog
  validations:
    required: true
- type: input
  id: site-desc
  attributes:
    label: 简介
    description: Description
    placeholder: 生如夏花之绚烂，死如秋叶之静美。
  validations:
    required: true
- type: input
  id: site-link
  attributes:
    label: 链接
    description: Link
    placeholder: https://qwq.blue
  validations:
    required: true
- type: input
  id: site-img
  attributes:
    label: 头像
    description: Avatar
    placeholder: https://wsrv.nl/?url=avatars.githubusercontent.com/u/184231508
  validations:
    required: true
